"""
Recommendation Engine - Component for generating actionable recommendations.

This module implements the Recommendation_Engine component that generates
rule-based recommendations, finds safe routes, and classifies urgency levels
based on Urban Risk Scores and accessibility reports.

Requirements: 5.1, 5.2, 5.3, 5.4, 5.5
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone, timedelta
from enum import Enum
from typing import Dict, List, Optional, Set
import logging
import math

from sqlalchemy.orm import Session

from src.uris_ai.models.database import Recommendation, Region, Road
from src.uris_ai.ml.flood_risk_engine import RiskCategory
from src.uris_ai.ml.service_accessibility import AccessibilityReport

# Configure logging
logger = logging.getLogger(__name__)


class RecommendationType(str, Enum):
    """Type of recommendation generated by the engine."""
    ROUTE = "route"
    ALERT = "alert"
    SERVICE = "service"


class UrgencyLevel(str, Enum):
    """
    Urgency classification for recommendations.

    - SEGERA: Immediate action required (within 1 hour)
    - WASPADA: Watch and prepare (1-6 hours)
    - SIAGA: Standby and monitor (6-24 hours)
    """
    SEGERA = "Segera"
    WASPADA = "Waspada"
    SIAGA = "Siaga"


@dataclass
class Coordinate:
    """Geographic coordinate (latitude, longitude)."""
    latitude: float
    longitude: float


@dataclass
class RecommendationItem:
    """
    A single recommendation generated by the engine.

    Attributes:
        region_id: ID of the region this recommendation applies to
        type: Type of recommendation (ROUTE, ALERT, SERVICE)
        description: Human-readable description in Bahasa Indonesia
        urgency: Urgency level (SEGERA, WASPADA, SIAGA)
        created_at: When the recommendation was created
        expires_at: When the recommendation expires (optional)
        metadata: Additional data specific to the recommendation type
    """
    region_id: int
    type: RecommendationType
    description: str
    urgency: UrgencyLevel
    created_at: datetime
    expires_at: Optional[datetime] = None
    metadata: Dict = field(default_factory=dict)


@dataclass
class RouteRecommendation:
    """
    A safe route recommendation from origin to destination.

    Attributes:
        origin: Starting coordinate
        destination: Destination coordinate
        route_region_ids: Ordered list of region IDs forming the route
        is_safe: Whether a safe route was found
        avoided_regions: Set of high-risk region IDs that were avoided
        no_safe_route_reason: Explanation if no safe route found
        estimated_recovery_hours: Estimated hours until safe route available
    """
    origin: Coordinate
    destination: Coordinate
    route_region_ids: List[int]
    is_safe: bool
    avoided_regions: Set[int] = field(default_factory=set)
    no_safe_route_reason: Optional[str] = None
    estimated_recovery_hours: Optional[float] = None


# Risk score threshold that triggers recommendation generation
RISK_SCORE_THRESHOLD = 70.0

# High-risk categories that routes must avoid
HIGH_RISK_CATEGORIES = {RiskCategory.TINGGI, RiskCategory.KRITIS}

# Urgency time windows (hours)
URGENCY_SEGERA_MAX_HOURS = 1.0
URGENCY_WASPADA_MAX_HOURS = 6.0
URGENCY_SIAGA_MAX_HOURS = 24.0


class RecommendationEngine:
    """
    Engine for generating actionable recommendations based on risk analysis.

    This class generates rule-based recommendations for government officials,
    facility managers, and the public based on Urban Risk Scores and
    accessibility reports.

    Requirements: 5.1, 5.2, 5.3, 5.4, 5.5
    """

    def __init__(
        self,
        db_session: Optional[Session] = None,
        risk_map: Optional[Dict[int, float]] = None,
    ):
        """
        Initialize the Recommendation Engine.

        Args:
            db_session: SQLAlchemy database session for persistence and queries
            risk_map: Optional pre-loaded mapping of region_id to urban_risk_score.
                      Used for route finding without requiring a live DB query.
        """
        self.db_session = db_session
        # risk_map caches current risk scores for route-finding logic
        self._risk_map: Dict[int, float] = risk_map or {}
        logger.info("RecommendationEngine initialized")

    def update_risk_map(self, risk_map: Dict[int, float]) -> None:
        """
        Update the internal risk map used for route finding.

        Args:
            risk_map: Mapping of region_id to urban_risk_score (0-100)
        """
        self._risk_map = risk_map
        logger.debug(f"Risk map updated with {len(risk_map)} regions")

    # ------------------------------------------------------------------
    # 12.2  generate_recommendations
    # ------------------------------------------------------------------

    def generate_recommendations(
        self,
        region_id: int,
        urban_risk_score: float,
        accessibility_report: Optional[AccessibilityReport] = None,
    ) -> List[RecommendationItem]:
        """
        Generate actionable recommendations for a region.

        Recommendations are generated when urban_risk_score > 70 (threshold).
        Rule-based logic produces ALERT, SERVICE, and ROUTE recommendations
        depending on the risk level and accessibility status.

        Args:
            region_id: ID of the region
            urban_risk_score: Current Urban Risk Score (0-100)
            accessibility_report: Optional accessibility report from
                                   Service_Accessibility_Module

        Returns:
            List of RecommendationItem objects, empty if score <= threshold

        Requirements: 5.1, 5.3
        """
        if urban_risk_score < 0 or urban_risk_score > 100:
            raise ValueError(
                f"urban_risk_score must be in [0, 100], got {urban_risk_score}"
            )

        recommendations: List[RecommendationItem] = []

        if urban_risk_score <= RISK_SCORE_THRESHOLD:
            logger.debug(
                f"Region {region_id} URS={urban_risk_score:.1f} below threshold "
                f"({RISK_SCORE_THRESHOLD}), no recommendations generated"
            )
            return recommendations

        now = datetime.now(timezone.utc)
        risk_category = self._score_to_category(urban_risk_score)
        urgency = self._score_to_urgency(urban_risk_score)

        # --- ALERT recommendation (always generated above threshold) ---
        alert_desc = self._build_alert_description(region_id, urban_risk_score, risk_category)
        recommendations.append(
            RecommendationItem(
                region_id=region_id,
                type=RecommendationType.ALERT,
                description=alert_desc,
                urgency=urgency,
                created_at=now,
                expires_at=now + timedelta(hours=URGENCY_SIAGA_MAX_HOURS),
                metadata={"risk_score": urban_risk_score, "category": risk_category.value},
            )
        )

        # --- SERVICE recommendation (when accessibility report provided) ---
        if accessibility_report and accessibility_report.overload_warnings:
            service_desc = self._build_service_description(
                accessibility_report.overload_warnings,
                accessibility_report.alternative_facilities,
            )
            recommendations.append(
                RecommendationItem(
                    region_id=region_id,
                    type=RecommendationType.SERVICE,
                    description=service_desc,
                    urgency=urgency,
                    created_at=now,
                    expires_at=now + timedelta(hours=URGENCY_WASPADA_MAX_HOURS),
                    metadata={
                        "overload_facilities": accessibility_report.overload_warnings,
                        "alternatives": accessibility_report.alternative_facilities,
                    },
                )
            )

        # --- ROUTE recommendation (for critical risk) ---
        if risk_category == RiskCategory.KRITIS:
            route_desc = (
                f"Wilayah {region_id} berada dalam kondisi KRITIS. "
                "Hindari perjalanan ke wilayah ini. "
                "Gunakan rute alternatif yang menghindari wilayah berisiko tinggi."
            )
            recommendations.append(
                RecommendationItem(
                    region_id=region_id,
                    type=RecommendationType.ROUTE,
                    description=route_desc,
                    urgency=UrgencyLevel.SEGERA,
                    created_at=now,
                    expires_at=now + timedelta(hours=URGENCY_SEGERA_MAX_HOURS),
                    metadata={"risk_category": risk_category.value},
                )
            )

        logger.info(
            f"Generated {len(recommendations)} recommendations for region {region_id} "
            f"(URS={urban_risk_score:.1f})"
        )
        return recommendations

    # ------------------------------------------------------------------
    # 12.3  find_safe_route
    # ------------------------------------------------------------------

    def find_safe_route(
        self,
        origin: Coordinate,
        destination: Coordinate,
        region_graph: Optional[Dict[int, List[int]]] = None,
        region_coordinates: Optional[Dict[int, Coordinate]] = None,
    ) -> RouteRecommendation:
        """
        Find a safe route from origin to destination avoiding high-risk regions.

        Uses a greedy nearest-neighbour / BFS approach over the region graph.
        Regions with RiskCategory TINGGI or KRITIS are treated as blocked nodes.

        If no safe route exists, returns a RouteRecommendation with
        is_safe=False and an explanation message.

        Args:
            origin: Starting coordinate
            destination: Destination coordinate
            region_graph: Adjacency list mapping region_id to list of
                          neighbouring region_ids.  If None, the method
                          attempts to build a graph from the database.
            region_coordinates: Mapping of region_id to Coordinate.
                                 Required when region_graph is provided
                                 without a DB session.

        Returns:
            RouteRecommendation with the safe route or failure explanation

        Requirements: 5.2, 5.5
        """
        # Build graph from DB if not supplied
        if region_graph is None:
            region_graph, region_coordinates = self._build_region_graph()

        if not region_graph:
            return RouteRecommendation(
                origin=origin,
                destination=destination,
                route_region_ids=[],
                is_safe=False,
                no_safe_route_reason=(
                    "Tidak ada data jaringan wilayah yang tersedia untuk "
                    "menemukan rute aman."
                ),
                estimated_recovery_hours=None,
            )

        # Identify high-risk (blocked) regions
        blocked: Set[int] = {
            rid
            for rid, score in self._risk_map.items()
            if self._score_to_category(score) in HIGH_RISK_CATEGORIES
        }

        # Find origin and destination regions
        origin_region = self._nearest_region(origin, region_coordinates)
        dest_region = self._nearest_region(destination, region_coordinates)

        if origin_region is None or dest_region is None:
            return RouteRecommendation(
                origin=origin,
                destination=destination,
                route_region_ids=[],
                is_safe=False,
                no_safe_route_reason=(
                    "Tidak dapat menentukan wilayah asal atau tujuan dari "
                    "koordinat yang diberikan."
                ),
            )

        if origin_region == dest_region:
            # Same region — check if it is safe
            if origin_region in blocked:
                return RouteRecommendation(
                    origin=origin,
                    destination=destination,
                    route_region_ids=[origin_region],
                    is_safe=False,
                    avoided_regions=blocked,
                    no_safe_route_reason=(
                        f"Wilayah asal dan tujuan (ID: {origin_region}) "
                        "berada dalam kondisi risiko tinggi."
                    ),
                    estimated_recovery_hours=self._estimate_recovery_hours(origin_region),
                )
            return RouteRecommendation(
                origin=origin,
                destination=destination,
                route_region_ids=[origin_region],
                is_safe=True,
                avoided_regions=blocked,
            )

        # BFS to find shortest safe path
        route = self._bfs_safe_path(
            origin_region, dest_region, region_graph, blocked
        )

        if route:
            logger.info(
                f"Safe route found: {len(route)} regions, "
                f"avoided {len(blocked)} high-risk regions"
            )
            return RouteRecommendation(
                origin=origin,
                destination=destination,
                route_region_ids=route,
                is_safe=True,
                avoided_regions=blocked,
            )

        # No safe route found
        recovery_hours = self._estimate_recovery_hours(dest_region)
        reason = (
            "Tidak dapat menemukan rute aman ke tujuan karena seluruh jalur "
            "melewati wilayah dengan risiko Tinggi atau Kritis."
        )
        if recovery_hours is not None:
            reason += (
                f" Estimasi waktu pemulihan: {recovery_hours:.1f} jam "
                "berdasarkan data historis."
            )

        logger.warning(
            f"No safe route found from region {origin_region} to {dest_region}. "
            f"Blocked regions: {len(blocked)}"
        )
        return RouteRecommendation(
            origin=origin,
            destination=destination,
            route_region_ids=[],
            is_safe=False,
            avoided_regions=blocked,
            no_safe_route_reason=reason,
            estimated_recovery_hours=recovery_hours,
        )

    # ------------------------------------------------------------------
    # 12.5  classify_urgency
    # ------------------------------------------------------------------

    def classify_urgency(
        self,
        time_to_impact_hours: float,
    ) -> UrgencyLevel:
        """
        Classify urgency level based on estimated time to impact.

        Time windows:
        - 0 ≤ t ≤ 1 hour  → SEGERA  (immediate action required)
        - 1 < t ≤ 6 hours → WASPADA (watch and prepare)
        - 6 < t ≤ 24 hours → SIAGA  (standby and monitor)
        - t > 24 hours     → SIAGA  (treated as lowest urgency)

        Args:
            time_to_impact_hours: Estimated hours until impact occurs.
                                   Must be non-negative.

        Returns:
            UrgencyLevel enum value

        Raises:
            ValueError: If time_to_impact_hours is negative

        Requirements: 5.4
        """
        if time_to_impact_hours < 0:
            raise ValueError(
                f"time_to_impact_hours must be non-negative, "
                f"got {time_to_impact_hours}"
            )

        if time_to_impact_hours <= URGENCY_SEGERA_MAX_HOURS:
            return UrgencyLevel.SEGERA
        elif time_to_impact_hours <= URGENCY_WASPADA_MAX_HOURS:
            return UrgencyLevel.WASPADA
        else:
            return UrgencyLevel.SIAGA

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _score_to_category(self, score: float) -> RiskCategory:
        """Convert a numeric risk score to a RiskCategory."""
        if score <= 25:
            return RiskCategory.RENDAH
        elif score <= 50:
            return RiskCategory.SEDANG
        elif score <= 75:
            return RiskCategory.TINGGI
        else:
            return RiskCategory.KRITIS

    def _score_to_urgency(self, urban_risk_score: float) -> UrgencyLevel:
        """
        Derive urgency from urban risk score.

        - Score > 90 (KRITIS extreme) → SEGERA
        - Score 76-90 (KRITIS)        → WASPADA
        - Score 71-75 (TINGGI high)   → SIAGA
        """
        if urban_risk_score > 90:
            return UrgencyLevel.SEGERA
        elif urban_risk_score > 75:
            return UrgencyLevel.WASPADA
        else:
            return UrgencyLevel.SIAGA

    def _build_alert_description(
        self,
        region_id: int,
        score: float,
        category: RiskCategory,
    ) -> str:
        """Build a human-readable alert description in Bahasa Indonesia."""
        category_labels = {
            RiskCategory.RENDAH: "Rendah",
            RiskCategory.SEDANG: "Sedang",
            RiskCategory.TINGGI: "Tinggi",
            RiskCategory.KRITIS: "Kritis",
        }
        label = category_labels.get(category, category.value)
        return (
            f"Peringatan risiko urban untuk wilayah {region_id}: "
            f"Skor Risiko Urban = {score:.1f} (Kategori: {label}). "
            "Segera lakukan tindakan pencegahan dan siapkan respons darurat."
        )

    def _build_service_description(
        self,
        overload_warnings: List[int],
        alternative_facilities: Dict[int, List[int]],
    ) -> str:
        """Build a service recommendation description in Bahasa Indonesia."""
        facility_list = ", ".join(str(fid) for fid in overload_warnings)
        desc = (
            f"Fasilitas publik berikut berpotensi kelebihan kapasitas: {facility_list}. "
        )
        if alternative_facilities:
            desc += "Fasilitas alternatif tersedia. Silakan gunakan fasilitas terdekat yang masih beroperasi."
        return desc

    def _build_region_graph(
        self,
    ) -> tuple[Dict[int, List[int]], Dict[int, Coordinate]]:
        """
        Build a region adjacency graph from the database.

        Two regions are considered neighbours if they share a road network
        (simplified: all regions are connected to each other for MVP).
        In production this would use spatial adjacency data.

        Returns:
            Tuple of (adjacency_dict, coordinate_dict)
        """
        if self.db_session is None:
            return {}, {}

        regions = self.db_session.query(Region).all()
        graph: Dict[int, List[int]] = {}
        coords: Dict[int, Coordinate] = {}

        for region in regions:
            coords[region.region_id] = Coordinate(
                latitude=region.latitude,
                longitude=region.longitude,
            )
            # Connect to all other regions (simplified full-mesh for MVP)
            graph[region.region_id] = [
                r.region_id for r in regions if r.region_id != region.region_id
            ]

        return graph, coords

    def _nearest_region(
        self,
        coord: Coordinate,
        region_coordinates: Optional[Dict[int, Coordinate]],
    ) -> Optional[int]:
        """Return the region_id whose centroid is closest to coord."""
        if not region_coordinates:
            return None

        best_id = None
        best_dist = float("inf")

        for rid, rc in region_coordinates.items():
            dist = self._haversine(
                coord.latitude, coord.longitude,
                rc.latitude, rc.longitude,
            )
            if dist < best_dist:
                best_dist = dist
                best_id = rid

        return best_id

    def _bfs_safe_path(
        self,
        start: int,
        goal: int,
        graph: Dict[int, List[int]],
        blocked: Set[int],
    ) -> Optional[List[int]]:
        """
        BFS to find the shortest path from start to goal avoiding blocked nodes.

        The start node is allowed even if blocked (user is already there).
        The goal node must NOT be blocked.

        Returns:
            Ordered list of region_ids forming the path, or None if not found.
        """
        if goal in blocked:
            return None

        from collections import deque

        queue: deque[List[int]] = deque([[start]])
        visited: Set[int] = {start}

        while queue:
            path = queue.popleft()
            current = path[-1]

            if current == goal:
                return path

            for neighbour in graph.get(current, []):
                if neighbour in visited:
                    continue
                if neighbour in blocked and neighbour != goal:
                    continue
                visited.add(neighbour)
                queue.append(path + [neighbour])

        return None

    def _estimate_recovery_hours(self, region_id: int) -> Optional[float]:
        """
        Estimate recovery time for a region based on historical data.

        For MVP, returns a fixed estimate based on risk score.
        In production, this would query historical flood duration data.

        Args:
            region_id: ID of the region

        Returns:
            Estimated recovery hours, or None if unknown
        """
        score = self._risk_map.get(region_id)
        if score is None:
            return None

        # Simplified estimate: higher risk → longer recovery
        if score > 90:
            return 24.0
        elif score > 75:
            return 12.0
        elif score > 50:
            return 6.0
        else:
            return 2.0

    @staticmethod
    def _haversine(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
        """Calculate great-circle distance in km using the Haversine formula."""
        R = 6371.0
        lat1_r, lon1_r = math.radians(lat1), math.radians(lon1)
        lat2_r, lon2_r = math.radians(lat2), math.radians(lon2)
        dlat = lat2_r - lat1_r
        dlon = lon2_r - lon1_r
        a = math.sin(dlat / 2) ** 2 + math.cos(lat1_r) * math.cos(lat2_r) * math.sin(dlon / 2) ** 2
        return R * 2 * math.asin(math.sqrt(a))
