#!/bin/bash

# URIS-AI Azure Infrastructure Setup Script
# This script sets up the Azure infrastructure using Terraform

set -e

echo "=========================================="
echo "URIS-AI Azure Infrastructure Setup"
echo "=========================================="
echo ""

# Check if Azure CLI is installed
if ! command -v az &> /dev/null; then
    echo "Error: Azure CLI is not installed."
    echo "Please install Azure CLI: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    exit 1
fi

# Check if Terraform is installed
if ! command -v terraform &> /dev/null; then
    echo "Error: Terraform is not installed."
    echo "Please install Terraform: https://www.terraform.io/downloads"
    exit 1
fi

# Check if logged in to Azure
echo "Checking Azure login status..."
if ! az account show &> /dev/null; then
    echo "Not logged in to Azure. Please login..."
    az login
fi

# Get current subscription
SUBSCRIPTION_ID=$(az account show --query id -o tsv)
SUBSCRIPTION_NAME=$(az account show --query name -o tsv)
echo "Current subscription: $SUBSCRIPTION_NAME ($SUBSCRIPTION_ID)"
echo ""

# Confirm subscription
read -p "Is this the correct subscription? (y/n) " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Please select the correct subscription using: az account set --subscription <subscription-id>"
    exit 1
fi

# Navigate to Terraform directory
cd infrastructure/terraform

# Check if terraform.tfvars exists
if [ ! -f "terraform.tfvars" ]; then
    echo "Error: terraform.tfvars not found."
    echo "Please copy terraform.tfvars.example to terraform.tfvars and fill in your values."
    exit 1
fi

# Initialize Terraform
echo "Initializing Terraform..."
terraform init

# Validate Terraform configuration
echo "Validating Terraform configuration..."
terraform validate

# Plan Terraform deployment
echo "Planning Terraform deployment..."
terraform plan -out=tfplan

# Confirm deployment
echo ""
read -p "Do you want to apply this Terraform plan? (y/n) " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Deployment cancelled."
    exit 0
fi

# Apply Terraform deployment
echo "Applying Terraform deployment..."
terraform apply tfplan

# Get outputs
echo ""
echo "=========================================="
echo "Deployment Complete!"
echo "=========================================="
echo ""
terraform output

# Save outputs to .env file
echo ""
echo "Saving configuration to .env file..."
cd ../..

# Create .env file from outputs
cat > .env << EOF
# Azure Configuration (Generated by setup_azure.sh)
AZURE_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
AZURE_TENANT_ID=$(az account show --query tenantId -o tsv)
AZURE_RESOURCE_GROUP=$(terraform -chdir=infrastructure/terraform output -raw resource_group_name)
AZURE_LOCATION=southeastasia

# Azure SQL Database
AZURE_SQL_SERVER=$(terraform -chdir=infrastructure/terraform output -raw sql_server_fqdn)
AZURE_SQL_DATABASE=uris-ai-db
AZURE_SQL_USERNAME=sqladmin
AZURE_SQL_PASSWORD=<YOUR_SQL_PASSWORD>
AZURE_SQL_CONNECTION_STRING=<WILL_BE_SET_BY_TERRAFORM>

# Azure Blob Storage
AZURE_STORAGE_ACCOUNT_NAME=$(terraform -chdir=infrastructure/terraform output -raw storage_account_name)
AZURE_STORAGE_CONNECTION_STRING=<WILL_BE_SET_BY_TERRAFORM>
AZURE_STORAGE_CONTAINER_RAW_DATA=raw-data
AZURE_STORAGE_CONTAINER_PROCESSED_DATA=processed-data

# Azure Key Vault
AZURE_KEY_VAULT_URL=$(terraform -chdir=infrastructure/terraform output -raw key_vault_uri)

# Azure Cache for Redis
REDIS_HOST=$(terraform -chdir=infrastructure/terraform output -raw redis_hostname)
REDIS_PORT=6380
REDIS_URL=<WILL_BE_SET_BY_TERRAFORM>

# Application URLs
API_URL=$(terraform -chdir=infrastructure/terraform output -raw api_url)
DASHBOARD_URL=$(terraform -chdir=infrastructure/terraform output -raw dashboard_url)

# Application Configuration
APP_NAME=URIS-AI
APP_VERSION=0.1.0
APP_ENV=development
DEBUG=true
LOG_LEVEL=INFO

# Security (CHANGE THESE IN PRODUCTION!)
SECRET_KEY=$(openssl rand -hex 32)
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30

# External APIs
WEATHER_API_URL=https://api.bmkg.go.id/publik/prakiraan-cuaca
WEATHER_API_KEY=<YOUR_WEATHER_API_KEY>
OSM_API_URL=https://overpass-api.de/api/interpreter

# Feature Flags
ENABLE_CACHING=true
ENABLE_RATE_LIMITING=true
ENABLE_MONITORING=true
EOF

echo ""
echo "Configuration saved to .env file."
echo "Please update the following values in .env:"
echo "  - AZURE_SQL_PASSWORD"
echo "  - WEATHER_API_KEY"
echo ""
echo "Setup complete!"
